#----------------------------------------------------------------------
#-- 描述: 这是用来构建本服务 OpenJ9 虚拟机镜像的 Dockerfile 文件.
#-- 作者: chenjiayin
#-- 日期: 2022-09-04
#-- 构建: docker build -t blinkfox/springboot-demo:openj9-scc -f src/main/docker/Dockerfile-openj9-scc .
#-- 运行: docker run -d -p 7072:7070 --name=springboot-demo-openj9-scc -v /Users/blinkfox/dev/cache/scc:/var/cache/scc blinkfox/springboot-demo:openj9-scc
#----------------------------------------------------------------------

FROM ibm-semeru-runtimes:open-17-jre

COPY target/springboot-demo.jar /springboot-demo.jar

VOLUME ["/var/cache/scc"]

EXPOSE 7070

ENTRYPOINT java -jar -Xshareclasses:cacheDir=/var/cache/scc /springboot-demo.jar
