#----------------------------------------------------------------------
#-- 描述: 这是用来构建本服务 HotSpot 虚拟机镜像的 Dockerfile 文件.
#-- 作者: chenjiayin
#-- 日期: 2022-09-04
#-- 构建: docker build -t blinkfox/springboot-demo:hotspot -f src/main/docker/Dockerfile-hotspot .
#-- 运行: docker run -d -p 7070:7070 --name=springboot-demo-hotspot blinkfox/springboot-demo:hotspot
#----------------------------------------------------------------------

FROM eclipse-temurin:17-jre

COPY target/springboot-demo.jar /springboot-demo.jar

EXPOSE 7070

ENTRYPOINT java -jar /springboot-demo.jar
